package testing;

import java.util.Date;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.Id;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.OneToOne;
import jakarta.persistence.Table;
import jakarta.persistence.Temporal;
import jakarta.persistence.TemporalType;

@Entity
@Table(name = "vehicle")
public class Vehicle {
	
	@Id
	@Column(name = "vehicle_id")
	private String vehicleId;
	
	@Column(name = "vehicle_type")
	private String typeOfVehicle;
	
	@Temporal(TemporalType.DATE)
	@Column(name = "dateOfPurchase")
	private Date dateOfPurchase;
	
	@Column(name = "vehicle_milage")
	private double milageOfVehicle;
	
	@Column(name = "gear_type")
	private String geartype;
	
	@OneToOne
	@JoinColumn(name ="cust_id")
	private Customer customer;
	
	public Customer getCustomer() {
		return customer;
	}

	public void setCustomer(Customer customer) {
		this.customer = customer;
	}

	public Vehicle() {
		
	}

	public String getVehicleId() {
		return vehicleId;
	}
	
	//Vehicle ID needs to be set because it is not autogenerated. It is set on the basis of type of the vehicle.
	public void setVehicleId(String vehicleId) {
		this.vehicleId = vehicleId;
}

	public String getTypeOfVehicle() {
		return typeOfVehicle;
	}

	public void setTypeOfVehicle(String typeOfVehicle) {
		this.typeOfVehicle = typeOfVehicle;
	}
	
	public Date getDateOfPurchase() {
		return dateOfPurchase;
	}

	public void setDateOfPurchase(Date dateOfPurchase) {
		this.dateOfPurchase = dateOfPurchase;
	}

	public double getMilageOfVehicle() {
		return milageOfVehicle;
	}

	public void setMilageOfVehicle(double milageOfVehicle) {
		this.milageOfVehicle = milageOfVehicle;
	}

	public String getGeartype() {
		return geartype;
	}

	public void setGeartype(String geartype) {
		this.geartype = geartype;
	}


}
